site_name: "GA4GH"

theme:
  name: mkdocs
  nav_style: dark

plugins:
  - search

docs_dir: docs
site_dir: mkdocs_html

nav:
  - Home: index.md

site_url: https://sujaypatil96.github.io/ga4gh-schema/
repo_url: https://sujaypatil96.github.io/ga4gh-schema/
